version: '2'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      main:
  client:
    build: ./client
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_WS_URL=http://localhost:3002
    networks:
      main:
  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - WS_URL=http://ws:3002
      - DB_URL=mongodb://db/events
    networks:
      main:
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]
  ws:
    build: ./ws
    command: npm start
    ports:
      - "3002:3002"
    environment:
      - API_URL=http://api:3001
    networks:
      main:
volumes:
  data:
networks:
  main: